### ISSUE TITLE
Menu screens return to title screen when "Cancel" is selected

### ISSUE THREAD

**Issue by meffij** [digiholic/universalSmashSystem#10]
Rather than putting the user back to the title screen, maybe they should be returned to the screen they were on previously. I'm not sure if this functionality is intended, or is intended to be upgraded in the future.

Steps to replicate:
Press start.
Go to settings menu.
Go to sound menu.
Hit Cancel. 
Be returned to title screen instead of settings menu.

**Comment by digiholic** [comment]
Fixed as of [5285adc](https://github.com/digiholic/universalSmashSystem/commit/5285adc8cc9b5618c43d2b3e3469930adf4d02ec)
