### ISSUE TITLE
Time battles still enforce stock limit

### ISSUE THREAD

**Issue by meffij** [digiholic/universalSmashSystem#12]
Even if you select Time battle, the game is still over after you lose however many stocks were set on the rules screen. There seems to be no difference between Time and Stock battles, they are both over when either time runs out or someone runs out of stocks, whichever comes first.

**Comment by digiholic** [comment]
Right now, it's looking like we're going to remove that option. If you want to not be limited by one of those, set it to zero, which is currently being treated as infinity.

**Comment by digiholic** [comment]
Fixed as of [5285adc](https://github.com/digiholic/universalSmashSystem/commit/5285adc8cc9b5618c43d2b3e3469930adf4d02ec)
