### ISSUE TITLE
Add shebang to main.py

### ISSUE THREAD

**Issue by eaglgenes101** [digiholic/universalSmashSystem#7]
Most linux users will probably try to run Tussle by double-clicking main.py or using the command line to execute it. Can you add the line #!/usr/bin/env python to the first line so this results in the expected behavior?

**Comment by digiholic** [comment]
Taken care of in [88d4a6](https://github.com/digiholic/universalSmashSystem/commit/88d4a6f92eea9e656ca3c053bee82e52abb0bf1c)

Thanks for bringing this to my attention.
