### ISSUE TITLE
CSS does not respect Sound Effect Volume setting

### ISSUE THREAD

**Issue by meffij** [digiholic/universalSmashSystem#9]
Despite setting the sound effect volume to 0.0, the CSS still produces a sound effect whenever I switch between characters.

Steps to reproduce:
Set sfxvolume to 0.0 in settings.ini
python main.py
Navigate to CSS. Notice that menus up to this point are not producing sound effects.
On the CSS, switch characters by pressing left or right. The sound effect will play.

As a side note, the sound effect has a variable delay of a few ms, so spamming left or right on the CSS produces a weird lag effect. This probably has to do with whatever facility is used to produce the sound effect being tied to system calls, but I assume there's some way for pygame to produce better-timed sound effects. I'll submit a new issue report if I figure anything more out about the delay.

**Comment by meffij** [comment]
Pull Request submitted

**Comment by ghost** [comment]
Thanks, approved your pull request!
